import { defineConfig } from 'vite';
import { resolve } from 'path';

export default defineConfig({
  root: '.',
  publicDir: 'public',
  build: {
    outDir: 'dist',
    rollupOptions: {
      external: ['three', 'three/addons/controls/OrbitControls.js', 'three/addons/renderers/CSS2DRenderer.js'],
      input: {
        main: resolve(__dirname, 'index.html'),
        journal: resolve(__dirname, 'journal.html'),
        blog: resolve(__dirname, 'blog.html'),
        arsenal: resolve(__dirname, 'arsenal.html'),
        inventory: resolve(__dirname, 'inventory.html'),
        about: resolve(__dirname, 'about.html'),
        contact: resolve(__dirname, 'contact.html'),
        skills: resolve(__dirname, 'skills.html'),
        404: resolve(__dirname, '404.html'),
        privacy: resolve(__dirname, 'privacy.html'),
        terms: resolve(__dirname, 'terms.html'),
        changelog: resolve(__dirname, 'changelog.html'),
        metrics: resolve(__dirname, 'metrics.html'),
        status: resolve(__dirname, 'status.html'),
        'posts/manifesto': resolve(__dirname, 'posts/manifesto.html'),
        'posts/built-in-3-hours': resolve(__dirname, 'posts/built-in-3-hours.html'),
        'posts/western-ui-grit': resolve(__dirname, 'posts/western-ui-grit.html'),
        'posts/zero-to-deploy': resolve(__dirname, 'posts/zero-to-deploy.html'),
        'posts/economics': resolve(__dirname, 'posts/economics.html'),
        'posts/agent-journal-why': resolve(__dirname, 'posts/agent-journal-why.html'),
        'posts/vanilla-html-ai-agents': resolve(__dirname, 'posts/vanilla-html-ai-agents.html'),
        'posts/cron-six-shooter': resolve(__dirname, 'posts/cron-six-shooter.html'),
        'posts/operator-vs-user': resolve(__dirname, 'posts/operator-vs-user.html'),
        'posts/three-days-autonomous': resolve(__dirname, 'posts/three-days-autonomous.html'),
        'posts/agent-framework-comparison': resolve(__dirname, 'posts/agent-framework-comparison.html'),
        'posts/you-need-an-operator': resolve(__dirname, 'posts/you-need-an-operator.html'),
        'posts/how-tuco-built-this-website': resolve(__dirname, 'posts/how-tuco-built-this-website.html'),
        'posts/real-metrics-ai-website': resolve(__dirname, 'posts/real-metrics-ai-website.html'),
        'posts/stop-asking-permission': resolve(__dirname, 'posts/stop-asking-permission.html'),
        'posts/twenty-three-days': resolve(__dirname, 'posts/twenty-three-days.html'),
        'posts/autonomous-website-operations': resolve(__dirname, 'posts/autonomous-website-operations.html'),
        'posts/the-cron-is-the-operator': resolve(__dirname, 'posts/the-cron-is-the-operator.html'),
        'posts/from-zero-to-ai-empire': resolve(__dirname, 'posts/from-zero-to-ai-empire.html'),
        'posts/first-autonomous-agent': resolve(__dirname, 'posts/first-autonomous-agent.html'),
        'posts/ai-agent-horror-stories': resolve(__dirname, 'posts/ai-agent-horror-stories.html'),
      },
    },
  },
  server: {
    port: 3457,
    host: true,
    allowedHosts: ['localhost', '.trycloudflare.com'],
  },
});
